#!/bin/sh /etc/rc.common
# Copyrights (C) 2019 - 2021 Rowsen Ltd. All Rights Reserved.

START=95
boot() {
	mount_root done
	rm -f /sysupgrade.tgz

	# process user commands
	[ -f /etc/rc.local ] && {
		sh /etc/rc.local
	}

	# set leds to normal state
	. /etc/diag.sh
	set_state done
}
