#!/bin/sh
# Copyrights (C) 2019 - 2021 Rowsen Ltd. All Rights Reserved.

export HOTPLUG_TYPE="$1"

. /lib/functions.sh

PATH="%PATH%"
LOGNAME=root
USER=root
export PATH LOGNAME USER
export DEVICENAME="${DEVPATH##*/}"

[ \! -z "$1" -a -d /etc/hotplug.d/$1 ] && {
	for script in $(ls /etc/hotplug.d/$1/* 2>&-); do (
		[ -f $script ] && . $script
	); done
}
