#!/bin/sh
#
# Copyrights (C) 2019 - 2021 Rowsen Ltd. All Rights Reserved.
#

. /lib/functions/uci-defaults.sh

board_config_update

json_is_a network object && exit 0

ucidef_set_interface_lan 'eth0'
[ -d /sys/class/net/eth1 ] && ucidef_set_interface_wan 'eth1'

board_config_flush

exit 0
