#!/bin/sh
# Copyrights (C) 2019 - 2021 Rowsen Ltd. All Rights Reserved.
# Copyright (C) 2010 Vertical Communications

# commands for emitting messages to network in failsafe mode

indicate_failsafe_led () {
	set_state failsafe
}

indicate_failsafe() {
	[ "$pi_preinit_no_failsafe" = "y" ] && return
	echo "- failsafe -"
	preinit_net_echo "Entering Failsafe!\n"
	indicate_failsafe_led
}

boot_hook_add failsafe indicate_failsafe
