#!/bin/sh
# Copyrights (C) 2019 - 2021 Rowsen Ltd. All Rights Reserved.
# Copyright (C) 2010 Vertical Communications

run_failsafe_hook() {
    [ "$pi_preinit_no_failsafe" = "y" ] && return
    if [ "$FAILSAFE" = "true" ]; then
	lock /tmp/.failsafe
	boot_run_hook failsafe
	while [ ! -e /tmp/sysupgrade ]; do
	    lock -w /tmp/.failsafe
	done
	exit
    fi
}

boot_hook_add preinit_main run_failsafe_hook
