#!/bin/sh
# Copyrights (C) 2019 - 2021 Rowsen Ltd. All Rights Reserved.
# Copyright (C) 2010 Vertical Communications

indicate_regular_preinit() {
	preinit_net_echo "Continuing with Regular Preinit\n"
	set_state preinit_regular
}

boot_hook_add preinit_main indicate_regular_preinit
