#!/bin/sh
# Copyrights (C) 2019 - 2021 Rowsen Ltd. All Rights Reserved.
# Copyright (C) 2010 Vertical Communications

initramfs_test() {
	if [ -n "$INITRAMFS" ]; then
		boot_run_hook initramfs
		preinit_ip_deconfig
		break
	fi
}

boot_hook_add preinit_main initramfs_test
